/*
 * HEAT API
 * The HEAT <u><b>INTERACTIVE</b></u> REST API, 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AccountInternetAddress class
 */
@Schema(description = "AccountInternetAddress class")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-28T22:39:51.557155300+03:00[Europe/Helsinki]")
public class AccountInternetAddress {
  @SerializedName("account")
  private String account = null;

  @SerializedName("internetAddress")
  private String internetAddress = null;

  @SerializedName("height")
  private Integer height = null;

  public AccountInternetAddress account(String account) {
    this.account = account;
    return this;
  }

   /**
   * The account id
   * @return account
  **/
  @Schema(required = true, description = "The account id")
  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public AccountInternetAddress internetAddress(String internetAddress) {
    this.internetAddress = internetAddress;
    return this;
  }

   /**
   * Registered host for account
   * @return internetAddress
  **/
  @Schema(required = true, description = "Registered host for account")
  public String getInternetAddress() {
    return internetAddress;
  }

  public void setInternetAddress(String internetAddress) {
    this.internetAddress = internetAddress;
  }

  public AccountInternetAddress height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Height of registration
   * @return height
  **/
  @Schema(required = true, description = "Height of registration")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountInternetAddress accountInternetAddress = (AccountInternetAddress) o;
    return Objects.equals(this.account, accountInternetAddress.account) &&
        Objects.equals(this.internetAddress, accountInternetAddress.internetAddress) &&
        Objects.equals(this.height, accountInternetAddress.height);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, internetAddress, height);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountInternetAddress {\n");
    
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    internetAddress: ").append(toIndentedString(internetAddress)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
