/*
 * HEAT API
 * The HEAT <u><b>INTERACTIVE</b></u> REST API, 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Transaction;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * BlockCondensed class
 */
@Schema(description = "BlockCondensed class")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-28T22:39:51.557155300+03:00[Europe/Helsinki]")
public class BlockCondensed {
  @SerializedName("totalAmountHQT")
  private String totalAmountHQT = null;

  @SerializedName("generator")
  private String generator = null;

  @SerializedName("generatorPublicName")
  private String generatorPublicName = null;

  @SerializedName("numberOfTransactions")
  private Integer numberOfTransactions = null;

  @SerializedName("totalFeeHQT")
  private String totalFeeHQT = null;

  @SerializedName("block")
  private String block = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("timestamp")
  private Integer timestamp = null;

  @SerializedName("posRewardHQT")
  private String posRewardHQT = null;

  @SerializedName("popRewardHQT")
  private String popRewardHQT = null;

  @SerializedName("transactions")
  private List<Transaction> transactions = new ArrayList<Transaction>();

  public BlockCondensed totalAmountHQT(String totalAmountHQT) {
    this.totalAmountHQT = totalAmountHQT;
    return this;
  }

   /**
   * The total amount in HQT (1 HQT equals 0.00000001 HEAT) of the transactions in the block
   * @return totalAmountHQT
  **/
  @Schema(required = true, description = "The total amount in HQT (1 HQT equals 0.00000001 HEAT) of the transactions in the block")
  public String getTotalAmountHQT() {
    return totalAmountHQT;
  }

  public void setTotalAmountHQT(String totalAmountHQT) {
    this.totalAmountHQT = totalAmountHQT;
  }

  public BlockCondensed generator(String generator) {
    this.generator = generator;
    return this;
  }

   /**
   * The generating account number
   * @return generator
  **/
  @Schema(required = true, description = "The generating account number")
  public String getGenerator() {
    return generator;
  }

  public void setGenerator(String generator) {
    this.generator = generator;
  }

  public BlockCondensed generatorPublicName(String generatorPublicName) {
    this.generatorPublicName = generatorPublicName;
    return this;
  }

   /**
   * The generator public name
   * @return generatorPublicName
  **/
  @Schema(required = true, description = "The generator public name")
  public String getGeneratorPublicName() {
    return generatorPublicName;
  }

  public void setGeneratorPublicName(String generatorPublicName) {
    this.generatorPublicName = generatorPublicName;
  }

  public BlockCondensed numberOfTransactions(Integer numberOfTransactions) {
    this.numberOfTransactions = numberOfTransactions;
    return this;
  }

   /**
   * The number of transactions in the block
   * @return numberOfTransactions
  **/
  @Schema(required = true, description = "The number of transactions in the block")
  public Integer getNumberOfTransactions() {
    return numberOfTransactions;
  }

  public void setNumberOfTransactions(Integer numberOfTransactions) {
    this.numberOfTransactions = numberOfTransactions;
  }

  public BlockCondensed totalFeeHQT(String totalFeeHQT) {
    this.totalFeeHQT = totalFeeHQT;
    return this;
  }

   /**
   * The total fee in HQT (1 HQT equals 0.00000001 HEAT) of the transactions in the block
   * @return totalFeeHQT
  **/
  @Schema(required = true, description = "The total fee in HQT (1 HQT equals 0.00000001 HEAT) of the transactions in the block")
  public String getTotalFeeHQT() {
    return totalFeeHQT;
  }

  public void setTotalFeeHQT(String totalFeeHQT) {
    this.totalFeeHQT = totalFeeHQT;
  }

  public BlockCondensed block(String block) {
    this.block = block;
    return this;
  }

   /**
   * The block ID
   * @return block
  **/
  @Schema(required = true, description = "The block ID")
  public String getBlock() {
    return block;
  }

  public void setBlock(String block) {
    this.block = block;
  }

  public BlockCondensed height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * The zero-based block height
   * @return height
  **/
  @Schema(required = true, description = "The zero-based block height")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public BlockCondensed timestamp(Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp (in seconds since 24 november 2013 00:00 UTC) of the block
   * @return timestamp
  **/
  @Schema(required = true, description = "The timestamp (in seconds since 24 november 2013 00:00 UTC) of the block")
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }

  public BlockCondensed posRewardHQT(String posRewardHQT) {
    this.posRewardHQT = posRewardHQT;
    return this;
  }

   /**
   * The total POS miner fee in HQT (1 HQT equals 0.00000001 HEAT)
   * @return posRewardHQT
  **/
  @Schema(required = true, description = "The total POS miner fee in HQT (1 HQT equals 0.00000001 HEAT)")
  public String getPosRewardHQT() {
    return posRewardHQT;
  }

  public void setPosRewardHQT(String posRewardHQT) {
    this.posRewardHQT = posRewardHQT;
  }

  public BlockCondensed popRewardHQT(String popRewardHQT) {
    this.popRewardHQT = popRewardHQT;
    return this;
  }

   /**
   * The total POP fee in HQT (1 HQT equals 0.00000001 HEAT)
   * @return popRewardHQT
  **/
  @Schema(required = true, description = "The total POP fee in HQT (1 HQT equals 0.00000001 HEAT)")
  public String getPopRewardHQT() {
    return popRewardHQT;
  }

  public void setPopRewardHQT(String popRewardHQT) {
    this.popRewardHQT = popRewardHQT;
  }

  public BlockCondensed transactions(List<Transaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public BlockCondensed addTransactionsItem(Transaction transactionsItem) {
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * An array of transaction IDs or transaction objects (if includeTransactions provided, refer to Get Transaction for details)
   * @return transactions
  **/
  @Schema(required = true, description = "An array of transaction IDs or transaction objects (if includeTransactions provided, refer to Get Transaction for details)")
  public List<Transaction> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<Transaction> transactions) {
    this.transactions = transactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockCondensed blockCondensed = (BlockCondensed) o;
    return Objects.equals(this.totalAmountHQT, blockCondensed.totalAmountHQT) &&
        Objects.equals(this.generator, blockCondensed.generator) &&
        Objects.equals(this.generatorPublicName, blockCondensed.generatorPublicName) &&
        Objects.equals(this.numberOfTransactions, blockCondensed.numberOfTransactions) &&
        Objects.equals(this.totalFeeHQT, blockCondensed.totalFeeHQT) &&
        Objects.equals(this.block, blockCondensed.block) &&
        Objects.equals(this.height, blockCondensed.height) &&
        Objects.equals(this.timestamp, blockCondensed.timestamp) &&
        Objects.equals(this.posRewardHQT, blockCondensed.posRewardHQT) &&
        Objects.equals(this.popRewardHQT, blockCondensed.popRewardHQT) &&
        Objects.equals(this.transactions, blockCondensed.transactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalAmountHQT, generator, generatorPublicName, numberOfTransactions, totalFeeHQT, block, height, timestamp, posRewardHQT, popRewardHQT, transactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockCondensed {\n");
    
    sb.append("    totalAmountHQT: ").append(toIndentedString(totalAmountHQT)).append("\n");
    sb.append("    generator: ").append(toIndentedString(generator)).append("\n");
    sb.append("    generatorPublicName: ").append(toIndentedString(generatorPublicName)).append("\n");
    sb.append("    numberOfTransactions: ").append(toIndentedString(numberOfTransactions)).append("\n");
    sb.append("    totalFeeHQT: ").append(toIndentedString(totalFeeHQT)).append("\n");
    sb.append("    block: ").append(toIndentedString(block)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    posRewardHQT: ").append(toIndentedString(posRewardHQT)).append("\n");
    sb.append("    popRewardHQT: ").append(toIndentedString(popRewardHQT)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
