/*
 * HEAT API
 * The HEAT <u><b>INTERACTIVE</b></u> REST API, 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DecryptedData class
 */
@Schema(description = "DecryptedData class")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-28T22:39:51.557155300+03:00[Europe/Helsinki]")
public class DecryptedData {
  @SerializedName("message")
  private String message = null;

  @SerializedName("isText")
  private Boolean isText = false;

  public DecryptedData message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Unencrypted data as either UTF-8 text or encoded as HEX (since binary)
   * @return message
  **/
  @Schema(required = true, description = "Unencrypted data as either UTF-8 text or encoded as HEX (since binary)")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public DecryptedData isText(Boolean isText) {
    this.isText = isText;
    return this;
  }

   /**
   * Indicates if message holds UTF-8 or HEX encoded binary data
   * @return isText
  **/
  @Schema(required = true, description = "Indicates if message holds UTF-8 or HEX encoded binary data")
  public Boolean isIsText() {
    return isText;
  }

  public void setIsText(Boolean isText) {
    this.isText = isText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DecryptedData decryptedData = (DecryptedData) o;
    return Objects.equals(this.message, decryptedData.message) &&
        Objects.equals(this.isText, decryptedData.isText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, isText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DecryptedData {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    isText: ").append(toIndentedString(isText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
