/*
 * HEAT API
 * The HEAT <u><b>INTERACTIVE</b></u> REST API, 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Fees class
 */
@Schema(description = "Fees class")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-28T22:39:51.557155300+03:00[Europe/Helsinki]")
public class Fees {
  @SerializedName("arbitraryMessageFee")
  private String arbitraryMessageFee = null;

  @SerializedName("ordinaryPaymentFee")
  private String ordinaryPaymentFee = null;

  @SerializedName("orderCancellationFee")
  private String orderCancellationFee = null;

  @SerializedName("orderPlacementFee")
  private String orderPlacementFee = null;

  @SerializedName("assetTransferFee")
  private String assetTransferFee = null;

  public Fees arbitraryMessageFee(String arbitraryMessageFee) {
    this.arbitraryMessageFee = arbitraryMessageFee;
    return this;
  }

   /**
   * Get arbitraryMessageFee
   * @return arbitraryMessageFee
  **/
  @Schema(description = "")
  public String getArbitraryMessageFee() {
    return arbitraryMessageFee;
  }

  public void setArbitraryMessageFee(String arbitraryMessageFee) {
    this.arbitraryMessageFee = arbitraryMessageFee;
  }

  public Fees ordinaryPaymentFee(String ordinaryPaymentFee) {
    this.ordinaryPaymentFee = ordinaryPaymentFee;
    return this;
  }

   /**
   * Get ordinaryPaymentFee
   * @return ordinaryPaymentFee
  **/
  @Schema(description = "")
  public String getOrdinaryPaymentFee() {
    return ordinaryPaymentFee;
  }

  public void setOrdinaryPaymentFee(String ordinaryPaymentFee) {
    this.ordinaryPaymentFee = ordinaryPaymentFee;
  }

  public Fees orderCancellationFee(String orderCancellationFee) {
    this.orderCancellationFee = orderCancellationFee;
    return this;
  }

   /**
   * Get orderCancellationFee
   * @return orderCancellationFee
  **/
  @Schema(description = "")
  public String getOrderCancellationFee() {
    return orderCancellationFee;
  }

  public void setOrderCancellationFee(String orderCancellationFee) {
    this.orderCancellationFee = orderCancellationFee;
  }

  public Fees orderPlacementFee(String orderPlacementFee) {
    this.orderPlacementFee = orderPlacementFee;
    return this;
  }

   /**
   * Get orderPlacementFee
   * @return orderPlacementFee
  **/
  @Schema(description = "")
  public String getOrderPlacementFee() {
    return orderPlacementFee;
  }

  public void setOrderPlacementFee(String orderPlacementFee) {
    this.orderPlacementFee = orderPlacementFee;
  }

  public Fees assetTransferFee(String assetTransferFee) {
    this.assetTransferFee = assetTransferFee;
    return this;
  }

   /**
   * Get assetTransferFee
   * @return assetTransferFee
  **/
  @Schema(description = "")
  public String getAssetTransferFee() {
    return assetTransferFee;
  }

  public void setAssetTransferFee(String assetTransferFee) {
    this.assetTransferFee = assetTransferFee;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fees fees = (Fees) o;
    return Objects.equals(this.arbitraryMessageFee, fees.arbitraryMessageFee) &&
        Objects.equals(this.ordinaryPaymentFee, fees.ordinaryPaymentFee) &&
        Objects.equals(this.orderCancellationFee, fees.orderCancellationFee) &&
        Objects.equals(this.orderPlacementFee, fees.orderPlacementFee) &&
        Objects.equals(this.assetTransferFee, fees.assetTransferFee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arbitraryMessageFee, ordinaryPaymentFee, orderCancellationFee, orderPlacementFee, assetTransferFee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fees {\n");
    
    sb.append("    arbitraryMessageFee: ").append(toIndentedString(arbitraryMessageFee)).append("\n");
    sb.append("    ordinaryPaymentFee: ").append(toIndentedString(ordinaryPaymentFee)).append("\n");
    sb.append("    orderCancellationFee: ").append(toIndentedString(orderCancellationFee)).append("\n");
    sb.append("    orderPlacementFee: ").append(toIndentedString(orderPlacementFee)).append("\n");
    sb.append("    assetTransferFee: ").append(toIndentedString(assetTransferFee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
