/*
 * HEAT API
 * The HEAT <u><b>INTERACTIVE</b></u> REST API, 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FullHash class
 */
@Schema(description = "FullHash class")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-28T22:39:51.557155300+03:00[Europe/Helsinki]")
public class FullHash {
  @SerializedName("fullHash")
  private String fullHash = null;

  @SerializedName("transaction")
  private String transaction = null;

  public FullHash fullHash(String fullHash) {
    this.fullHash = fullHash;
    return this;
  }

   /**
   * The full hash of the signed transaction
   * @return fullHash
  **/
  @Schema(required = true, description = "The full hash of the signed transaction")
  public String getFullHash() {
    return fullHash;
  }

  public void setFullHash(String fullHash) {
    this.fullHash = fullHash;
  }

  public FullHash transaction(String transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * The transaction ID
   * @return transaction
  **/
  @Schema(required = true, description = "The transaction ID")
  public String getTransaction() {
    return transaction;
  }

  public void setTransaction(String transaction) {
    this.transaction = transaction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullHash fullHash = (FullHash) o;
    return Objects.equals(this.fullHash, fullHash.fullHash) &&
        Objects.equals(this.transaction, fullHash.transaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullHash, transaction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullHash {\n");
    
    sb.append("    fullHash: ").append(toIndentedString(fullHash)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
