/*
 * HEAT API
 * The HEAT <u><b>INTERACTIVE</b></u> REST API, 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Hallmark class
 */
@Schema(description = "Hallmark class")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-28T22:39:51.557155300+03:00[Europe/Helsinki]")
public class HallmarkResponse {
  @SerializedName("hallmark")
  private String hallmark = null;

  public HallmarkResponse hallmark(String hallmark) {
    this.hallmark = hallmark;
    return this;
  }

   /**
   * The hallmark hex string
   * @return hallmark
  **/
  @Schema(required = true, description = "The hallmark hex string")
  public String getHallmark() {
    return hallmark;
  }

  public void setHallmark(String hallmark) {
    this.hallmark = hallmark;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HallmarkResponse hallmarkResponse = (HallmarkResponse) o;
    return Objects.equals(this.hallmark, hallmarkResponse.hallmark);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hallmark);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HallmarkResponse {\n");
    
    sb.append("    hallmark: ").append(toIndentedString(hallmark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
