/*
 * HEAT API
 * The HEAT <u><b>INTERACTIVE</b></u> REST API, 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Generic KeyStoreBundle class
 */
@Schema(description = "Generic KeyStoreBundle class")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-28T22:39:51.557155300+03:00[Europe/Helsinki]")
public class KeyStoreBundle {
  @SerializedName("account")
  private String account = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("transaction")
  private String transaction = null;

  public KeyStoreBundle account(String account) {
    this.account = account;
    return this;
  }

   /**
   * Account scope
   * @return account
  **/
  @Schema(required = true, description = "Account scope")
  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public KeyStoreBundle key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The key that identifies this entry
   * @return key
  **/
  @Schema(required = true, description = "The key that identifies this entry")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public KeyStoreBundle value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The entry value
   * @return value
  **/
  @Schema(required = true, description = "The entry value")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public KeyStoreBundle transaction(String transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * Transaction id for transaction that last set this entry
   * @return transaction
  **/
  @Schema(required = true, description = "Transaction id for transaction that last set this entry")
  public String getTransaction() {
    return transaction;
  }

  public void setTransaction(String transaction) {
    this.transaction = transaction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyStoreBundle keyStoreBundle = (KeyStoreBundle) o;
    return Objects.equals(this.account, keyStoreBundle.account) &&
        Objects.equals(this.key, keyStoreBundle.key) &&
        Objects.equals(this.value, keyStoreBundle.value) &&
        Objects.equals(this.transaction, keyStoreBundle.transaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, key, value, transaction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyStoreBundle {\n");
    
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
